<?php

/**
 * @file
 * Functions to support theming in the Curso drupal theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function curso_drupal_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function curso_drupal_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function curso_drupal_preprocess_node(&$variables) {
  $variables['precontent'] = 'Hello World!';
}
